name: "Check setup"
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        oscript_version: [lts, stable, dev]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    name: check oscript
    steps: 
    - uses: actions/checkout@v2 
    - uses: ./
      with:
        version: ${{ matrix.oscript_version }}
    - name: Проверка скрипта OS
      run: oscript test/fixtures/test.os
    - name: Проверка установки coverage
      run: opm install coverage
